/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.CursoDAO;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Curso;

/**
 *
 * @author Sala308b
 */
public class FrmCursos extends javax.swing.JInternalFrame {

    /**
     * Creates new form FrmAlunos
     */
    public FrmCursos() {
        initComponents();
        this.popularCursos();
    }

    public void popularCursos() {
        
        DefaultTableModel dtm = (DefaultTableModel) tblCursos.getModel();
        
        dtm.setNumRows(0);
        dtm.setColumnCount(0);
        String[] colunas = {"ID", "NOME","CARGA HORARIA"};
        
        dtm.setColumnIdentifiers(colunas);
        
        CursoDAO cursoDAO = new CursoDAO();
        cursoDAO.listar().forEach(( c ) -> {
        int id = c.getCursoId();
        String nome = c.getNome ();
        String cargaHoraria = String.valueOf (c.getCargaHoraria());
        
        String[] linha = { String.valueOf(id), nome, cargaHoraria        };
        
        dtm.addRow(linha);
        
    });
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        btnNovo = new java.awt.Button();
        btnSalvar = new java.awt.Button();
        txtNome = new java.awt.TextField();
        txtId = new java.awt.TextField();
        label1 = new java.awt.Label();
        Curso = new java.awt.Label();
        label3 = new java.awt.Label();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblCursos = new javax.swing.JTable();
        btnExcluir = new java.awt.Button();
        btnListar = new java.awt.Button();
        label2 = new java.awt.Label();
        txtCargaHoraria = new java.awt.TextField();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        setBackground(new java.awt.Color(210, 240, 240));
        setClosable(true);
        setForeground(new java.awt.Color(0, 0, 204));
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("CURSO");

        btnNovo.setForeground(new java.awt.Color(0, 0, 204));
        btnNovo.setLabel("Novo");
        btnNovo.setName("btnNovo"); // NOI18N
        btnNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoActionPerformed(evt);
            }
        });

        btnSalvar.setForeground(new java.awt.Color(0, 0, 204));
        btnSalvar.setLabel("Salvar");
        btnSalvar.setName("btnSalvar"); // NOI18N
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        txtNome.setName("txdNome"); // NOI18N
        txtNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeActionPerformed(evt);
            }
        });

        txtId.setEnabled(false);
        txtId.setName("txdId"); // NOI18N
        txtId.setText("0");
        txtId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdActionPerformed(evt);
            }
        });

        label1.setForeground(new java.awt.Color(0, 0, 204));
        label1.setText("ID");

        Curso.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        Curso.setForeground(new java.awt.Color(0, 0, 204));
        Curso.setText("Curso");

        label3.setForeground(new java.awt.Color(0, 0, 204));
        label3.setText("NOME");

        tblCursos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblCursos.setName("tblCursos"); // NOI18N
        tblCursos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblCursosMouseClicked(evt);
            }
        });
        tblCursos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tblCursosKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tblCursosKeyReleased(evt);
            }
        });
        jScrollPane3.setViewportView(tblCursos);

        btnExcluir.setForeground(new java.awt.Color(0, 0, 204));
        btnExcluir.setLabel("Excluir");
        btnExcluir.setName("btnExcluir"); // NOI18N
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        btnListar.setForeground(new java.awt.Color(0, 0, 204));
        btnListar.setLabel("Listar");
        btnListar.setName("btnListar"); // NOI18N
        btnListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarActionPerformed(evt);
            }
        });

        label2.setName("txtCargaHoraria"); // NOI18N
        label2.setText("Carga Horária");

        txtCargaHoraria.setName("txtCargaHoraria"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(283, 283, 283)
                        .addComponent(Curso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(74, 74, 74)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtNome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtId, javax.swing.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(31, 31, 31)
                                    .addComponent(txtCargaHoraria, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(18, 18, 18)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(40, 40, 40)
                                            .addComponent(btnNovo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(42, 42, 42)
                                            .addComponent(btnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(42, 42, 42)
                                            .addComponent(btnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(42, 42, 42)
                                            .addComponent(btnListar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 492, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addGap(93, 93, 93))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(Curso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33)
                        .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCargaHoraria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnNovo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnListar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(65, Short.MAX_VALUE))
        );

        btnNovo.getAccessibleContext().setAccessibleName("btnNovo");
        btnSalvar.getAccessibleContext().setAccessibleName("btnSalvar");
        btnExcluir.getAccessibleContext().setAccessibleName("btnExcluir");
        btnExcluir.getAccessibleContext().setAccessibleDescription("");
        btnListar.getAccessibleContext().setAccessibleName("btnListar");
        btnListar.getAccessibleContext().setAccessibleDescription("");
        label2.getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void editarDados(){
        
        int row = tblCursos.getSelectedRow();
        String id = tblCursos.getModel().getValueAt(row, 0).toString();
        String nome = tblCursos.getModel().getValueAt(row, 1).toString();
        String cargaHoraria = tblCursos.getModel().getValueAt(row, 2).toString();
        
        txtId.setText(id);
        txtNome.setText(nome);
        txtCargaHoraria.setText(cargaHoraria);
        
    }
    
    
    
    
    private void btnNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoActionPerformed
        // TODO add your handling code here:
        txtId.setText("0");
        txtNome.setText(" ");
        txtCargaHoraria.setText("0");
        
    }//GEN-LAST:event_btnNovoActionPerformed

    private void txtIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdActionPerformed

    private void txtNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeActionPerformed

    private void btnListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnListarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        // TODO add your handling code here:
       // CursoDao cursoDAO = new CursoDAO();
       
       CursoDAO cursoDAO = new CursoDAO();
       Curso curso = new Curso();
       int id = Integer.parseInt(txtId.getText());
       curso.setCursoId(id);
       
       boolean excluiu = cursoDAO.excluir(curso);
       
       if ( excluiu){
           JOptionPane.showMessageDialog(null, "Curso excluido com sucesso. ");
           popularCursos();
           }
       else {
              JOptionPane.showMessageDialog(null, "Erro ao tentar excluir o curso. ");
    }
       
       
       
       
        
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void tblCursosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblCursosMouseClicked
        // TODO add your handling code here:
        editarDados();
    }//GEN-LAST:event_tblCursosMouseClicked

    private void tblCursosKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tblCursosKeyPressed
        // TODO add your handling code here:
        editarDados();
    }//GEN-LAST:event_tblCursosKeyPressed

    private void tblCursosKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tblCursosKeyReleased
        // TODO add your handling code here:
        editarDados();
    }//GEN-LAST:event_tblCursosKeyReleased

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        // TODO add your handling code here:
        
        CursoDAO cursoDAO = new CursoDAO();
        Curso curso = new Curso();
        curso.setCursoId( Integer.parseInt(txtId.getText()));
        curso.setNome(txtNome.getText());
        curso.setCargaHoraria( Integer.parseInt(txtCargaHoraria.getText()));
        
        if (txtId.getText().equals("0")){
             boolean inclui = cursoDAO.incluir(curso);
                if (inclui ) {
                   JOptionPane.showMessageDialog(null,"Curso Incluindo com sucesso.  ");
                   popularCursos();
                } else {
                   JOptionPane.showMessageDialog(null,"Erro ao tentar incluir o curso  ");
                }
        } else {
            boolean atualizou = cursoDAO.atualizar(curso);
                if (atualizou ) {
                   JOptionPane.showMessageDialog(null,"Curso Atualizado com sucesso.  ");
                   popularCursos();
                } else {
                   JOptionPane.showMessageDialog(null,"Erro ao tentar atualizar o curso  ");
                }
        } 
    }//GEN-LAST:event_btnSalvarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Label Curso;
    private java.awt.Button btnExcluir;
    private java.awt.Button btnListar;
    private java.awt.Button btnNovo;
    private java.awt.Button btnSalvar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private java.awt.Label label1;
    private java.awt.Label label2;
    private java.awt.Label label3;
    private javax.swing.JTable tblCursos;
    private java.awt.TextField txtCargaHoraria;
    private java.awt.TextField txtId;
    private java.awt.TextField txtNome;
    // End of variables declaration//GEN-END:variables
}
