/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

/**
 *
 * @author Sala308b
 */
public class JanelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form JanelaPrincipal
     */
    public JanelaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        mnuAlunos = new javax.swing.JMenuItem();
        mnuCursos = new javax.swing.JMenuItem();
        mnuDisciplinas = new javax.swing.JMenuItem();
        mnuProfessores = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        mnuSair = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        jMenu1.setText("Sistema");

        jMenuItem2.setText("Login");
        jMenu1.add(jMenuItem2);
        jMenuItem2.getAccessibleContext().setAccessibleName("MnuLogin");

        jMenu1.add(jSeparator2);

        mnuAlunos.setText("Alunos");
        mnuAlunos.setName(""); // NOI18N
        mnuAlunos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuAlunosActionPerformed(evt);
            }
        });
        jMenu1.add(mnuAlunos);
        mnuAlunos.getAccessibleContext().setAccessibleName("MnuAlunos");

        mnuCursos.setText("Cursos");
        mnuCursos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuCursosActionPerformed(evt);
            }
        });
        jMenu1.add(mnuCursos);
        mnuCursos.getAccessibleContext().setAccessibleName("MnuCursos");

        mnuDisciplinas.setText("Disciplinas");
        mnuDisciplinas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuDisciplinasActionPerformed(evt);
            }
        });
        jMenu1.add(mnuDisciplinas);
        mnuDisciplinas.getAccessibleContext().setAccessibleName("MnuDisciplinas");

        mnuProfessores.setText("Professores");
        mnuProfessores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuProfessoresActionPerformed(evt);
            }
        });
        jMenu1.add(mnuProfessores);
        mnuProfessores.getAccessibleContext().setAccessibleName("MnuProfessores");

        jMenu1.add(jSeparator1);

        mnuSair.setText("Sair");
        jMenu1.add(mnuSair);
        mnuSair.getAccessibleContext().setAccessibleName("MnuSair");

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Ajuda");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnuCursosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuCursosActionPerformed
        // TODO add your handling code here:
        FrmCursos frmCursos = new FrmCursos();
        frmCursos.setVisible (true);
        
        this.jDesktopPane1.add(frmCursos);
        
    }//GEN-LAST:event_mnuCursosActionPerformed

    private void mnuAlunosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuAlunosActionPerformed
        // TODO add your handling code here:
        FrmAlunos frmAlunos = new FrmAlunos();
        frmAlunos.setVisible (true);
        
        this.jDesktopPane1.add(frmAlunos);
        
    }//GEN-LAST:event_mnuAlunosActionPerformed

    private void mnuDisciplinasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuDisciplinasActionPerformed
        // TODO add your handling code here:
        FrmDisciplinas frmDisciplinas = new FrmDisciplinas();
        frmDisciplinas.setVisible (true);
        
        this.jDesktopPane1.add(frmDisciplinas);
    }//GEN-LAST:event_mnuDisciplinasActionPerformed

    private void mnuProfessoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuProfessoresActionPerformed
        // TODO add your handling code here:
        
        FrmProfessores frmProfessores = new FrmProfessores();
        frmProfessores.setVisible (true);
        
        this.jDesktopPane1.add(frmProfessores);
    }//GEN-LAST:event_mnuProfessoresActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JanelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JanelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JanelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JanelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JanelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JMenuItem mnuAlunos;
    private javax.swing.JMenuItem mnuCursos;
    private javax.swing.JMenuItem mnuDisciplinas;
    private javax.swing.JMenuItem mnuProfessores;
    private javax.swing.JMenuItem mnuSair;
    // End of variables declaration//GEN-END:variables
}
